# Generated by Django 3.2.24 on 2024-02-29 15:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wishlist', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='wishlist',
            name='quantity',
            field=models.SmallIntegerField(default=1),
        ),
    ]
