# Generated by Django 3.2.24 on 2024-02-29 16:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('wishlist', '0002_wishlist_quantity'),
    ]

    operations = [
        migrations.RenameField(
            model_name='wishlist',
            old_name='quantity',
            new_name='wish_quantity',
        ),
    ]
