# Generated by Django 3.2.24 on 2024-03-01 15:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0001_initial'),
        ('wishlist', '0003_rename_quantity_wishlist_wish_quantity'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='wishlist',
            name='wish_quantity',
        ),
        migrations.AlterField(
            model_name='wishlist',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='profiles.userprofile'),
        ),
    ]
