# Generated by Django 3.2.24 on 2024-03-10 13:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0002_auto_20240310_1327'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='default_postalcode',
            field=models.CharField(blank=True, max_length=40, null=True),
        ),
    ]
