# Generated by Django 3.2.24 on 2024-03-10 14:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0003_alter_userprofile_default_postalcode'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='default_mobile_number',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
    ]
