# Generated by Django 3.2.24 on 2024-02-28 13:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contact', '0002_auto_20240228_0826'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contact',
            name='contact_subject',
            field=models.CharField(choices=[('Other', 'Other'), ('Plants', 'Plants'), ('Shipping & Delivery', 'Shipping & Delivery')], max_length=30),
        ),
    ]
