# Generated by Django 3.2.24 on 2024-03-10 13:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contact', '0002_alter_contact_contact_subject'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contact',
            name='contact_subject',
            field=models.CharField(choices=[('Other', 'Other'), ('Shipping & Delivery', 'Shipping & Delivery'), ('Plants', 'Plants')], max_length=30),
        ),
    ]
