# Generated by Django 3.2.24 on 2024-02-28 15:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contact', '0003_alter_contact_contact_subject'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contact',
            name='contact_subject',
            field=models.CharField(choices=[('Plants', 'Plants'), ('Shipping & Delivery', 'Shipping & Delivery'), ('Other', 'Other')], max_length=30),
        ),
    ]
