# Generated by Django 3.2.24 on 2024-03-10 14:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contact', '0003_alter_contact_contact_subject'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contact',
            name='contact_subject',
            field=models.CharField(choices=[('Plants', 'Plants'), ('Other', 'Other'), ('Shipping & Delivery', 'Shipping & Delivery')], max_length=30),
        ),
    ]
