# Generated by Django 3.2.24 on 2024-03-01 15:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contact', '0004_alter_contact_contact_subject'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contact',
            name='contact_subject',
            field=models.CharField(choices=[('Shipping & Delivery', 'Shipping & Delivery'), ('Plants', 'Plants'), ('Other', 'Other')], max_length=30),
        ),
    ]
