# Generated by Django 3.2.24 on 2024-02-29 15:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0004_product_has_size'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='has_size',
        ),
        migrations.RemoveField(
            model_name='product',
            name='stock',
        ),
    ]
